# Generated by Django 3.1.3 on 2020-11-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='occupied_platform',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
