# Generated by Django 3.1.3 on 2020-11-26 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_station_occupied_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatchart',
            name='train_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.train'),
        ),
    ]
