# Generated by Django 3.1.3 on 2020-11-27 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20201126_1024'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('station_id', 'date', 'train_id')},
        ),
    ]
