# Generated by Django 3.1.3 on 2020-12-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_seatchart_total_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatchart',
            name='total_seats',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
