# Generated by Django 3.1.3 on 2020-12-06 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
        ('scheduler', '0007_auto_20201206_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatchart',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authenticate.staffmember'),
        ),
    ]
