# Generated by Django 3.1.3 on 2020-12-06 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_auto_20201206_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainlegacy',
            name='route_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.route'),
        ),
    ]
