# Generated by Django 3.1.3 on 2020-12-13 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_auto_20201206_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainlegacy',
            name='old_train_id',
        ),
    ]
